### ISSUE TITLE
PHP Fatal error:  Uncaught Error

### ISSUE THREAD

**Issue by 3918831** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#10]
PHP Fatal error:  Uncaught Error: Call to undefined function openssl_decrypt() in bypass.php:230
Stack trace:
#0 bypass.php(330): decryptData('8/8Mnp7WcRph8sb...')
#1 {main}
  thrown in bypass.php on line 230

Fatal error: Uncaught Error: Call to undefined function openssl_decrypt() in bypass.php:230
Stack trace:
#0 bypass.php(330): decryptData('8/8Mnp7WcRph8sb...')
#1 {main}
  thrown in bypass.php on line 230

**Comment by DanRan-hcy** [comment]
没有开php的openssl扩展

**Comment by MlgmXyysd** [comment]
Duplicated #3
