### ISSUE TITLE
default 10000 request parameter error

### ISSUE THREAD

**Issue by conflagration27** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#100]
i have 14ultra, none of the settings.apk files helped to solve the problem. Now there is an option to unlock bl for CN 14 ultra with bypass?

**Comment by ketor** [comment]
According to the document of this project, 14ultra cannot bypass. Only devices with MIUI version before and installed HyperOS now can be bypassed.

**Comment by rossanodr** [comment]
any news on this?

**Comment by smile-YYY** [comment]
> any news on this?有这方面的消息吗？

You can install the new settings app, then log in to your Xiaomi account again, connect the phone to the computer to unlock it, this is how I solved the problem

**Comment by smile-YYY** [comment]
You can install the new settings app, then log in to your Xiaomi account again, connect the phone to the computer to unlock it, this is how I solved the problem

**Comment by conflagration27** [comment]
@smile-YYY 

For which model should there be a settings.apk version? For 14\14 pro\14 ultra there is no special version. I tried all versions for all models (although I did not re-login to my account every time I installed it), and no version worked.

**Comment by W1LLY-W0N** [comment]
Same here. Any news ?

**Comment by xbn2002** [comment]
Look https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/issues/82 pls
And if you can't open developer options after downgrade, then find another one until it works.

**Comment by xbn2002** [comment]
> @smile-YYY
> 
> For which model should there be a settings.apk version? For 14\14 pro\14 ultra there is no special version. I tried all versions for all models (although I did not re-login to my account every time I installed it), and no version worked.

Note that devices pre-installed HyperOS are not supported to bypass, thanks.

**Comment by xbn2002** [comment]
> same for me, xioami 14 ultra global get error 10000, same also with settings update

If you have a global device, then just go to international MI community and apply for authorization, click a few buttons and it will be done.
