### ISSUE TITLE
Binding failed, this device has been forced to verify the account qualification by Xiaomi. (30001)

### ISSUE THREAD

**Issue by Tigercat000** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#107]
K70 Pro was Binding failed, this device has been forced to verify the account qualification by Xiaomi. (30001)
It seem impossible to unlock right now .anyone can help ? Thanks.

**Comment by xbn2002** [comment]
No way, unless you spend money to find inner ghosts

**Comment by Tigercat000** [comment]
Got it , so I give up

**Comment by MANTKG** [comment]
Hi, could u solve it ?

**Comment by preetam1409** [comment]
same issue poco f6 didnt work , any way to fix it ?
