### ISSUE TITLE
 MI14 ULTRA got "Request parameter error (10000)" how to fix it?

### ISSUE THREAD

**Issue by bjqscilonr** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#109]
Warning: PHP Startup: Unable to load dynamic library 'pdo_oci' (tried: C:\php\ext\pdo_oci (?曆??唳?摰?璅∠???, C:\php\ext\php_pdo_oci.dll (?曆??唳?摰?璅∠???) in Unknown on line 0
[2024-04-27] [07:50:26] [INFO] - ************************************
[2024-04-27] [07:50:26] [INFO] - * Xiaomi HyperOS BootLoader Bypass *
[2024-04-27] [07:50:26] [INFO] - * By NekoYuzu          Version 1.0 *
[2024-04-27] [07:50:26] [INFO] - ************************************
[2024-04-27] [07:50:26] [INFO] - GitHub: https://github.com/MlgmXyysd
[2024-04-27] [07:50:26] [INFO] - XDA: https://xdaforums.com/m/mlgmxyysd.8430637
[2024-04-27] [07:50:26] [INFO] - X (Twitter): https://x.com/realMlgmXyysd
[2024-04-27] [07:50:26] [INFO] - PayPal: https://paypal.me/MlgmXyysd
[2024-04-27] [07:50:26] [INFO] - My Blog: https://www.neko.ink/
[2024-04-27] [07:50:26] [INFO] - ************************************
[2024-04-27] [07:50:26] [INFO] - Starting ADB server...
[2024-04-27] [07:50:29] [INFO] - Processing device 91a8f771(12)...
[2024-04-27] [07:50:30] [INFO] - Finding BootLoader unlock bind request...
[2024-04-27] [07:50:30] [INFO] * Now you can bind account in the developer options.
[2024-04-27] [07:50:34] [INFO] - Account bind request found! Let's block it.
[2024-04-27] [07:50:34] [INFO] - Refactoring parameters...
[2024-04-27] [07:50:34] [INFO] - Sending POST request...
[2024-04-27] [07:50:36] [INFO] - Request parameter error (10000)

**Comment by bjqscilonr** [comment]
![Screenshot_2024-04-27-15-52-52-312_com android settings](https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/assets/168264760/2a4997b6-b5e8-4da3-9a9f-4aee8fe4ee05)

**Comment by GigilinE** [comment]
same problem, for now 14 ultra is not possible :(

**Comment by bjqscilonr** [comment]
OMG.....

**Comment by p-hao** [comment]
It is probably a decryptData error, I got the same error
![image](https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/assets/76999093/9cb6d014-ea8a-4cdb-8a59-150502f82630)

**Comment by bjqscilonr** [comment]
if no more method to fix the final way will be.
https://item.taobao.com/item.htm?id=744221028275&spm=a1z0d.6639537/tb.1997196601.4.64ce5886lulaFm&skuId=5132145840928

**Comment by GigilinE** [comment]
> if no more method to fix the final way will be. https://item.taobao.com/item.htm?id=744221028275&spm=a1z0d.6639537/tb.1997196601.4.64ce5886lulaFm&skuId=5132145840928

what is this?

**Comment by bjqscilonr** [comment]
unlock HYPEROS BL by china taobao 3rd party vendor. 550RMB

**Comment by xbn2002** [comment]
Dowager settings, find a setting APK that can open the developer option, and cover the installation.

**Comment by AbdulrahmanAlamodi** [comment]
> unlock HYPEROS BL by china taobao 3rd party vendor. 550RMB

77.77$ 🥲

**Comment by xbn2002** [comment]
Btw, devices pre-installed HyperOS are not supported to use this tool

**Comment by AbdulrahmanAlamodi** [comment]
> Note that evices pre-installed HyperOS are not supported to bypass, thanks

Bro, I have currently Resmi K60 Pro already unlocked.
I just want to be prepared when I switch to another newer device, so I will try to get the required level on the Mi Community app by then, because third party solutions are very expensive 😭.
My question is, are there any other requirement beside increasing level, or it's just impossible.

**Comment by xbn2002** [comment]
> > Note that evices pre-installed HyperOS are not supported to bypass, thanks
> 
> Bro, I have currently Resmi K60 Pro already unlocked. I just want to be prepared when I switch to another newer device, so I will try to get the required level on the Mi Community app by then, because third party solutions are very expensive 😭. My question is, are there any other requirement beside increasing level, or it's just impossible.

Oh, I see.
I recommend you buy devices at where you live, not from China, because getting the permission in China-mainland Mi Community is quite hard. Besides the growth level, you also have to pass a very hard exam (86 score can pass), and audit result is also unpredictable.
Therefore, although mainland China devices are cheaper, I still recommend that you buy international versions of devices because unlocking will be much more convenient.

**Comment by AbdulrahmanAlamodi** [comment]
> > > Note that evices pre-installed HyperOS are not supported to bypass, thanks
> > 
> > 
> > Bro, I have currently Resmi K60 Pro already unlocked. I just want to be prepared when I switch to another newer device, so I will try to get the required level on the Mi Community app by then, because third party solutions are very expensive 😭. My question is, are there any other requirement beside increasing level, or it's just impossible.
> 
> Oh, I see. I recommend you buy devices at where you live, not from China, because getting the permission in China-mainland Mi Community is quite hard. Besides the growth level, you also have to pass a very hard exam (86 score can pass), and audit result is also unpredictable. Therefore, although mainland China devices are cheaper, I still recommend that you buy international versions of devices because unlocking will be much more convenient.

Yes I know that, but the problem that I am in love with Ks Pro versions, and these versions are exclusive.
Well, thanks for reply, I think I might end up buying the paid service, because I can't live with locked bootloader.
