### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by ZhaiyuanC** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#11]
PHP Fatal error:  Uncaught Error: Call to undefined function openssl_decrypt() in D:\php-8.3.0-nts-Win32-vs16-x64\bypass.php:230
Stack trace:
#0 D:\php-8.3.0-nts-Win32-vs16-x64\bypass.php(330): decryptData('8/8Mnp7WcRph8sb...')
#1 {main}
  thrown in D:\php-8.3.0-nts-Win32-vs16-x64\bypass.php on line 230

Fatal error: Uncaught Error: Call to undefined function openssl_decrypt() in D:\php-8.3.0-nts-Win32-vs16-x64\bypass.php:230
Stack trace:
#0 D:\php-8.3.0-nts-Win32-vs16-x64\bypass.php(330): decryptData('8/8Mnp7WcRph8sb...')
#1 {main}
  thrown in D:\php-8.3.0-nts-Win32-vs16-x64\bypass.php on line 230

**Comment by MlgmXyysd** [comment]
Duplicated #3

**Comment by kiafas** [comment]
Hey I did these steps and no luck can you help me?

**Comment by kiafas** [comment]
Any help I did these steps and it still shoes up
