### ISSUE TITLE
bypass.php(330): decryptData('8/8Mnp7WcRph8sb...')

### ISSUE THREAD

**Issue by W1LLY-W0N** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#111]
Hey guys !

I am currently trying to unlock the bootloader of my Xiaomi 14 Ultra and I have this issue :

`Fatal error: Uncaught Error: Call to undefined function openssl_decrypt() in C:\Users\xuwil\Downloads\Unlock 2\bypass.php:230
Stack trace:
#0 C:\Users\xuwil\Downloads\Unlock 2\bypass.php(330): decryptData('8/8Mnp7WcRph8sb...')
#1 {main}
  thrown in C:\Users\xuwil\Downloads\Unlock 2\bypass.php on line 230`

I think I did something wrong but I do not know what, can someone help me ?

**Comment by fzj121382** [comment]
Hey bro!
 I'm having the same issue. Can you please tell me how you solved it? I can't do it alone.
