### ISSUE TITLE
Device is Xiaomi 14,using OS 1.0.26.0,computer is Windows 11 25931

### ISSUE THREAD

**Issue by somerui** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#114]
When I press"Add account and device" button,bypass script is stopped.

PHP Fatal error:  Uncaught Error: Call to undefined function openssl_decrypt() in C:\Users\this_\Downloads\Bypass-1.0-fix-universal\bypass.php:230
Stack trace:
#0 C:\Users\this_\Downloads\Bypass-1.0-fix-universal\bypass.php(330): decryptData('8/8Mnp7WcRph8sb...')
#1 {main}
  thrown in C:\Users\this_\Downloads\Bypass-1.0-fix-universal\bypass.php on line 230

Fatal error: Uncaught Error: Call to undefined function openssl_decrypt() in C:\Users\t\Downloads\Bypass-1.0-fix-universal\bypass.php:230
Stack trace:
#0 C:\Users\t\Downloads\Bypass-1.0-fix-universal\bypass.php(330): decryptData('8/8Mnp7WcRph8sb...')
#1 {main}
  thrown in C:\Users\t\Downloads\Bypass-1.0-fix-universal\bypass.php on line 230

**Comment by xuxin1955** [comment]
小米14不是出厂澎湃吗

**Comment by somerui** [comment]
草所以目前出厂澎湃还是无解对吧

**Comment by somerui** [comment]
傻逼小米
