### ISSUE TITLE
does xiaomi14Pro（China mainland）can usethis to unblock thebl？

### ISSUE THREAD

**Issue by 18505561765** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#116]

**Comment by W1LLY-W0N** [comment]
I tried but it didn't work. I think it's not possible using this way...

**Comment by xbn2002** [comment]
Devices pre-installed HyperOS are not supported

**Comment by xbn2002** [comment]
Note that evices pre-installed HyperOS are not supported to bypass, thanks
