### ISSUE TITLE
Can bootloader on Redmi Note 13 Pro 5G China version device be unlocked with this method?

### ISSUE THREAD

**Issue by spiderfix101** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#118]
Can bootloader on Redmi Note 13 Pro 5G China version device be unlocked?

**Comment by xbn2002** [comment]
No, Redmi Note 13 series will get the 30003 error code when try to bind account.
There's no solution now and in the future.

**Comment by spiderfix101** [comment]
> No, Redmi Note 13 series will get the 30003 error code when you try to bind account. There's no solution now and in the future.

What about Redmi Note 12 Turbo (China Version)? Is it possible to unlock the bootloader?

**Comment by xbn2002** [comment]
> > No, Redmi Note 13 series will get the 30003 error code when you try to bind account. There's no solution now and in the future.
> 
> What about Redmi Note 12 Turbo (China Version)? Is it possible to unlock the bootloader?

Just bypass as other series. Find a settings apk that can open developer options. #82

**Comment by JakoDel** [comment]
> No, Redmi Note 13 series will get the 30003 error code when you try to bind account. There's no solution now and in the future.

so it's basically impossible for global users to unlock new xiaomi phones bought from china like the redmi turbo 3, and extremely hard for chinese users. what a great job by xiaomi

**Comment by Boom-Hacker** [comment]
> No, Redmi Note 13 series will get the 30003 error code when you try to bind account. There's no solution now and in the future.

if they don't update the hyperos?in miui can note13 series bind and unlock?

**Comment by DEAL08** [comment]
I have a Redmi note 13 pro lifts 5g 2312DRA50C I already private the network method and nothing for me Unlock and nothing, Can someone help me please can you write to my WhatsApp I am in U.E +19547954722

**Comment by RuizeSun** [comment]
> I've even done it with the bypass through a PC and it gives me error 10000. What can I do? Someone can help me. I want my global ROM on my phone.

I also have error 10000. It's disgusting. Unlocking bootloader is the rights of users.

**Comment by RuizeSun** [comment]
> 我尝试使用此脚本解锁 Redmi Note 13 Pro 上的引导加载程序，并没有出现错误 30003。但我收到了错误：调用未定义的函数 openssl_decrypt.php
> 
> 但是我发现每次运行这个脚本的时候，移动数据都会自动关闭，导致手机无法连接到小米服务器。我认为解决移动数据关闭的问题可以让脚本成功绑定账号，然后解锁 bootloader。

you needs to install(or enable) the OpenSSL and Curl moudle in PHP, but it'll get error 10000 if you are using Redmi Note 13 series

**Comment by NayamAmarshe** [comment]
Is Xiaomi disabling Note 13 Pro devices?

**Comment by RuizeSun** [comment]
> Is Xiaomi disabling Note 13 Pro devices?

it looks like. there's no unlocking solutions in Note 13 series now. so i gave up on it

**Comment by Chihav** [comment]
So. it's a completely dead cause then. Such a shame bought this phone here in China, and went through hell to unlock it, I guess the only way is to keep farming till LVL5 and pas the quiz after this phone will be sent abroad, and then unlock it remotely.

**Comment by Wabogh** [comment]
Can someone please help me
I have a redmi note 12 turbo china hyperos
I've tried this method before and at first It gave me the 20045 error after that a I've tried again but with a vpn set up to hong Kong and it gave me the 10000 error instead (I've installed the patched setting app)
What can I do about this?

**Comment by nyaniscool** [comment]
It has been 2 years. Has anyone found the solution for this? Redmi note 13 pro 5g china

**Comment by RuizeSun** [comment]
> It has been 2 years. Has anyone found the solution for this? Redmi note 13 pro 5g china

As of now, looks like no dice unless you pull off some trick (probably gonna need to crack it open).
