### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: decryptData():

### ISSUE THREAD

**Issue by Tuiye** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#123]
PHP Fatal error:  Uncaught TypeError: decryptData(): Argument #1 ($data) must be of type string, null given, called in /xxx/Xiaomi-HyperOS-BootLoader-Bypass-master/bypass.php on line 330 and defined in /xxx/Xiaomi-HyperOS-BootLoader-Bypass-master/bypass.php:228
Stack trace:
#0 /xxx/Xiaomi-HyperOS-BootLoader-Bypass-master/bypass.php(330): decryptData(NULL)
#1 {main}
  thrown in /xxx/Xiaomi-HyperOS-BootLoader-Bypass-master/bypass.php on line 228

**Comment by Tuiye** [comment]
MacOS

**Comment by pulpoff** [comment]
same error on ubuntu as well

**Comment by popkter** [comment]
same error on Win11, install php env by xampp

**Comment by mhmdali711** [comment]
i have the same problem with my redmi turbo 3 chinese rom

**Comment by cnjsyyb** [comment]
根本不能用

**Comment by SergeTDU** [comment]
Has anyone figure it out? getting the same error
