### ISSUE TITLE
OpenSSL has been setup correctly，but throw exception PHP Fatal error:  Uncaught Error: Call to undefined function openssl_decrypt()  in bypass.php:230

### ISSUE THREAD

**Issue by popkter** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#137]
this is my phpinfo
![屏幕截图_30-6-2024_04458_localhost](https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/assets/74968459/80211b9e-14a9-4342-9dea-c36042864983)

when  i run bypass.cmd and click bind account on device，throw exception：
> 
![image](https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/assets/74968459/1aaad006-6eec-4f67-b8b3-60c6dade1cde)

I am not good at php, any one can help me? thank u very much!

**Comment by popkter** [comment]
oh god i find something wrong .if use cmd script ，it cannot find php extenstions even though I has add config to system path。if   cmd doesnot work, try run ` php bypass.php` directly.

**Comment by mhmdali711** [comment]
> oh god i find something wrong .if use cmd script ，it cannot find php extenstions even though I has add config to system path。if cmd doesnot work, try run ` php bypass.php` directly.

please any help with this problem

**Comment by Oyama-Oyama** [comment]
same error
any help？

**Comment by popkter** [comment]
> same error any help？

i directly run bypass.php to fix this error

**Comment by VitmaSense** [comment]
@popkter  Can you please explain how to get rid of the error?
