### ISSUE TITLE
Binding failed, this device has been forced to verify the account qualification by Xiaomi. (30001) 

### ISSUE THREAD

**Issue by SajidulAmlan** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#139]
Can anyone pls help me with it

**Comment by Terfik** [comment]
Got same error, after waiting time168h... Any solutions?

**Comment by KusakabeShi** [comment]
No. xiaomi updates their server, blocked this bypass tool for `Xiaomi Pad 6S Pro`, `Redmi Turbo 3` and `Xiaomi Civi 4 Pro`.

**Comment by uaevuon** [comment]
> No. Xiaomi updates their server, block this bypass tool for `Xiaomi Pad 6S Pro`, `Redmi Turbo 3` and `Xiaomi Civi 4 Pro` at 7/2/2024. These devices can no longer unlock it's bootloader. The only option is sell it and buy another model if you need root access.

If I used this tool last Friday(June 28th), can I still unlock my device? Mine is Turbo 3

**Comment by chenguang121** [comment]
You need to install the old version of the 'Settings.apk' APP

**Comment by HansLau** [comment]
> No. Xiaomi updates their server, block this bypass tool for `Xiaomi Pad 6S Pro`, `Redmi Turbo 3` and `Xiaomi Civi 4 Pro` at 7/2/2024. These devices can no longer unlock it's bootloader. The only option is sell it and buy another model if you need root access.

These are the only ones for now? Why these specific models?

**Comment by Cr4z33** [comment]
Add also the Redmi Pad Pro to the list.

**Comment by Jakeohararayess** [comment]
Add also the Redmi k70 Pro to the list.

**Comment by AlonsoK28** [comment]
**Poco F6** same problem

**Comment by wazzirul** [comment]
Poco X6 Pro same problem, already install old settings

**Comment by zirok3** [comment]
решили проблему?

**Comment by preetam1409** [comment]
> **Poco F6** same problem

yes same here

**Comment by ajajbihar** [comment]
poco x6 pro , bootloader unlock not done by php and Hypersploit software. please tale me anymore  tool , free our paid. thanks .

**Comment by balajivb19** [comment]
> Poco X6 Pro same problem, already install old settings

hello bhai same problem any solution u find it
