### ISSUE TITLE
Error in requesting parameters (10000)

### ISSUE THREAD

**Issue by ydwp** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#144]
Error in requesting parameters (10000)

**Comment by liboliu** [comment]
I have the same problem on XiaoMi 13.

**Comment by Amidler** [comment]
![image](https://github.com/user-attachments/assets/97486d77-10a8-49db-8159-55606767ba95)
same problem

**Comment by catlog66** [comment]
https://www.bilibili.com/read/cv33210239/
