### ISSUE TITLE
no longer work

### ISSUE THREAD

**Issue by rafivadra** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#145]
On the script it's says 

`[2024-07-20] [10:10:19] [INFO] - Account bound successfully, wait time can be viewed in the unlock tool.`

But on my settings it's still not binded to my account, still unbinded, and i tried to press the add account on my setting, it's says coulndt add again, verify blablabla on mi community

Help mee :3

**Comment by jdjnnxjdk** [comment]
scripts still working dud (240817) 

Even if ur phone hits 'not binded', sometimes it still working   (but may have to wait 168 h) Try using BL unlocking tool official
