### ISSUE TITLE
Please help for Note 13 Pro china version can unlock bootlaoder now?

### ISSUE THREAD

**Issue by Smartslabs** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#163]
Plaese help Note 13 Pro china version can unlock bootlaoder right now?
Xiaomi seem change rules resently.

**Comment by architelos** [comment]
Nah not yet; still throws 30003.

**Comment by Smartslabs** [comment]
> Nah not yet; still throws 30003.

sad to heard that,but thanks

**Comment by ALFAMAS** [comment]
still waiting with same problem
