### ISSUE TITLE
能否支持一下红米K70，欧版miui论坛反馈不支持

### ISSUE THREAD

**Issue by 000tv** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#18]
感谢大佬做出的杰出贡献，小米封解锁太坏了，小米本来就是从刷机起家的。。。

**Comment by SanGongHappy** [comment]
k70e 出现相同问题 ，报错 30001

**Comment by MlgmXyysd** [comment]
无解，小米服务器检测到这个设备代号就直接去判断你账号有没有权限了

**Comment by kaedea** [comment]
> 无解，小米服务器检测到这个设备代号就直接去判断你账号有没有权限了

按照这套逻辑，小米服务器是可以升级堵住本 Bypass 工具的漏洞的吗？

**Comment by MlgmXyysd** [comment]
> > 无解，小米服务器检测到这个设备代号就直接去判断你账号有没有权限了
> 
> 按照这套逻辑，小米服务器是可以升级堵住本 Bypass 工具的漏洞的吗？

出厂MIUI的老设备堵不了，除非把MIUI的解锁限制提升到和HyperOS一样。出厂就是HyperOS自然不会存在MIUI的版本，所以可以把这些设备拉个清单，强制走校验逻辑

**Comment by zhongwen-4** [comment]
> > > 无解，小米服务器检测到这个设备代号就直接去判断你账号有没有权限了
> > 
> > 
> > 按照这套逻辑，小米服务器是可以升级堵住本 Bypass 工具的漏洞的吗？
> 
> 出厂MIUI的老设备堵不了，除非把MIUI的解锁限制提升到和HyperOS一样。出厂就是HyperOS自然不会存在MIUI的版本，所以可以把这些设备拉个清单，强制走校验逻辑

纳尼？红米k70不支持？那没事了
