### ISSUE TITLE
Code is not detecting my phone

### ISSUE THREAD

**Issue by Sudharsshan** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#202]
I carried out the operations as exactly given in the instructions, but in the command prompt it just doesn't detect my phone or whatever?

I have **Redmi 13C 5G**, which i recently updated into HyperOS (seriously why did I even do that..)

This is what it shows in the command prompt when I execute the script:
<br>
![image](https://github.com/user-attachments/assets/edbe8f10-205e-4046-880a-9db38deaf570)
<br><br>
Even after unplugging out the phone and plugging it back in, it just doesn't get detected by the script. 
<br><br>
Any help is appreciated, Thanks!

**Comment by BlueNoob** [comment]
phone should be in FAST BOOT mode.

**Comment by Sudharsshan** [comment]
Thank you though I tried, it did not detect as the code requires you to unlock and connect the phone so that it can take you to the developer options menu.

**Comment by MihailoStarcevic** [comment]
Have you turned Windows real-time protection off? I had the same problem until I turned it off and then it started detecting the phone.

**Comment by noicl** [comment]
You need the adb.exe in your libraries folder. The libraries folder needs to be in the same folder as the bypass.php script.

Phone does not have to be in bootloader, just start it up normally

**Comment by Sudharsshan** [comment]
Hey thanks for your help, I tried it out yet it just won't detect my phone. I have just dropped it at this point and moved on to Samsung. 
Appreciate it guys thanks!
