### ISSUE TITLE
ADB已经连接了，但是脚本Waiting for device connection...

### ISSUE THREAD

**Issue by canmiwu** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#217]
![image](https://github.com/user-attachments/assets/c311ce71-06e0-49e3-8c96-39537099ae99)
![image](https://github.com/user-attachments/assets/6e0d7ac6-9684-4d04-af38-6166ce21930a)
![image](https://github.com/user-attachments/assets/a21bf300-ddfb-4e75-8164-5aece2bfab1a)
![image](https://github.com/user-attachments/assets/580965fa-b4d6-4db8-b962-9ce50d1e854e)
症状是，手机小米12S，开了ADB调试 OEM解锁，ADB安全调试，插上电脑资源管理识别了
![image](https://github.com/user-attachments/assets/62646c02-1bd8-4622-8c75-ec5d312ae6b4)
但是似乎一直卡在等待ADB连接这个界面，开始怀疑是我的问题，但是使用了秋之盒查看
![image](https://github.com/user-attachments/assets/1b5bcbe6-0634-47aa-be1d-357b085f48a1)
结果显示手机已连接，然后使用ADB查看
![image](https://github.com/user-attachments/assets/7330e683-5304-444f-9a96-dedee9a8d02a)

**Comment by kiwirafe** [comment]
您好 请问你是怎么解决的啊？

**Comment by MeaningOrca** [comment]
Same problem. Does somebody find the solution?
