### ISSUE TITLE
Bypass支持机型是不是不包括小米14？

### ISSUE THREAD

**Issue by AwcySama** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#25]
![image](https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/assets/34682022/b4ff93cb-91d6-4b89-8a5c-2a854d36c0a0)
这个怎么弄？？是不是不支持小米14

**Comment by MlgmXyysd** [comment]
https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/issues/18#issuecomment-1864172157
