### ISSUE TITLE
unsuccess to unlock （system version：1.0.20.0.UNCCNXM）

### ISSUE THREAD

**Issue by nenemiku** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#3]
看到其他的B站评论有说1.0.14以后的版本解锁会失败。我这边的操作是成功连接后，点击解锁移动数据被关闭，提示解锁失败，CMD里显示
 [INFO] - Refactoring parameters...
PHP Fatal error:  Uncaught Error: Call to undefined function openssl_decrypt() in J:\mi\php-8.3.0-nts-Win32-vs16-x64\bypass.php:230
Stack trace:
#0 J:\mi\php-8.3.0-nts-Win32-vs16-x64\bypass.php(330): decryptData('8/8Mnp7WcRph8sb...')
#1 {main}
  thrown in J:\mi\php-8.3.0-nts-Win32-vs16-x64\bypass.php on line 230

Fatal error: Uncaught Error: Call to undefined function openssl_decrypt() in J:\mi\php-8.3.0-nts-Win32-vs16-x64\bypass.php:230
Stack trace:
#0 J:\mi\php-8.3.0-nts-Win32-vs16-x64\bypass.php(330): decryptData('8/8Mnp7WcRph8sb...')
#1 {main}
  thrown in J:\mi\php-8.3.0-nts-Win32-vs16-x64\bypass.php on line 230

**Comment by MlgmXyysd** [comment]
https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass?tab=readme-ov-file#%EF%B8%8F-how-to-use

> Enable OpenSSL and Curl extension in php.ini.

**Comment by chrisuhg** [comment]
指定你php的ext文件夹位置。
![image](https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/assets/34882677/9c5663ce-c5a2-4937-a537-ef38f586679f)

**Comment by SVENDEMAN100** [comment]
This does NOT solve the issue unfortunately.

> 指定你php的ext文件夹位置。 ![image](https://private-user-images.githubusercontent.com/34882677/285495351-9c5663ce-c5a2-4937-a537-ef38f586679f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMDg3NTYsIm5iZiI6MTcyNTMwODQ1NiwicGF0aCI6Ii8zNDg4MjY3Ny8yODU0OTUzNTEtOWM1NjYzY2UtYzVhMi00OTM3LWE1MzctZWYzOGY1ODY2NzlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDIwMjA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1YjU0YTU3ODQ4YWIwYmFhYjUzNjllN2YzZTFjMjUxMWRjMTFkNDYwM2FhMjMyMTI4NWM3N2VhNTgwOTE3ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p9e6x-Z4RHZwjwCtkOAEGgvcGAQGITKWFUYNHmA2o1Q)
