### ISSUE TITLE
Request parameter error (10000)

### ISSUE THREAD

**Issue by symbianvn** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#33]
![image](https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/assets/8969143/a301bd58-f6bc-4a45-90d4-d3e2e673821b)

Plz help!

**Comment by MlgmXyysd** [comment]
Duplicate #29
https://twitter.com/realMlgmXyysd/status/1748386904050110675?s=19

**Comment by franc732** [comment]
I also have the same error

**Comment by max98889889** [comment]
хтось вирішив цю проблему?

**Comment by max98889889** [comment]
![0000](https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/assets/172954573/98ecfccf-d1c7-45ec-b8fe-59e46e8594d3)
              не працює цей спосіб (
