### ISSUE TITLE
Uncaught TypeError: decryptData

### ISSUE THREAD

**Issue by alzubaidi** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#4]
Fatal error: Uncaught TypeError: decryptData(): Argument #1 ($data) must be of type string, null given, called in `Xiaomi-HyperOS-BootLoader-Bypass-master/bypass.php` on line 333 and defined in `Xiaomi-HyperOS-BootLoader-Bypass-master/bypass.php:228`
Stack trace:
#0 `Xiaomi-HyperOS-BootLoader-Bypass-master/bypass.php(333)`: decryptData(NULL)
#1 {main}
  thrown in `Xiaomi-HyperOS-BootLoader-Bypass-master/bypass.php` on line 228

**Comment by MlgmXyysd** [comment]
Looks like logcat fetched null, try it again

**Comment by Windforce17** [comment]
Try set `id` to empty string if you are using new adb version and only one device connected.
```
$id = $adb -> getDeviceId($device[1], true);
$id="";
```

**Comment by alzubaidi** [comment]
Setting `$id` to empty string worked for me. However, it says
```
[2023-11-24] [15:06:50] [INFO] - Binding failed, this device has been forced to verify the account qualification by Xiaomi. (30001)
```

:(

**Comment by changyun233** [comment]
> Setting `$id` to empty string worked for me. However, it says
> 
> ```
> [2023-11-24] [15:06:50] [INFO] - Binding failed, this device has been forced to verify the account qualification by Xiaomi. (30001)
> ```
> 
> :(

same 30001 for me.

Device :Xiaomi 14 with 1.0.23.11.21.DEV

I had tried to apply for BL unlock in Xiaomishequ. Obviously I did not pass...

Jesus is there a Chinese brand Android phone with loose unlock policy...
