### ISSUE TITLE
成功绑定，但是miunlock错误1004

### ISSUE THREAD

**Issue by HARUKAZE707** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#42]
![image](https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/assets/54128903/8885dd2a-6cea-4e78-9612-440531d0e01b)
![image](https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/assets/54128903/15b32bcf-b802-4bbd-b30d-a9ac668d9d60)

**Comment by MlgmXyysd** [comment]
没见过的报错，估计小米服务器那边又在搞啥东西吧

**Comment by HARUKAZE707** [comment]
> 没见过的报错，估计小米服务器那边又在搞啥东西吧

我换成外版的mi unlock就成功了

**Comment by MlgmXyysd** [comment]
> > 没见过的报错，估计小米服务器那边又在搞啥东西吧
> 
> 我换成外版的mi unlock就成功了

好的
