### ISSUE TITLE
K50标准版；OS1.0.23.12.11.DEV

### ISSUE THREAD

**Issue by 931743010** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#43]
这里过不去了；不知道什么原因；是不是因为DEV版本不支持吗
![image](https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/assets/9315727/374f1341-2c53-4b8b-851f-a1b46b4804d7)

**Comment by MlgmXyysd** [comment]
直接执行adb logcat试一下呢

**Comment by 931743010** [comment]
已解决；需要退出小米账号；退出开发者模式；再操作就成功了。  之前只操作了退出小米账号；导致没成功。
