### ISSUE TITLE
Note 13 Pro + PHP Fatal Error Call to undefined function openssl_decrypt() in C:\php\bypass.php:230

### ISSUE THREAD

**Issue by encouragerv** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#45]
[2024-01-30] [11:43:15] [INFO] - Refactoring parameters...
PHP Fatal error:  Uncaught Error: Call to undefined function openssl_decrypt() in C:\php\bypass.php:230
Stack trace:
#0 C:\php\bypass.php(330): decryptData('8/8Mnp7WcRph8sb...')
#1 {main}
  thrown in C:\php\bypass.php on line 230

Fatal error: Uncaught Error: Call to undefined function openssl_decrypt() in C:\php\bypass.php:230
Stack trace:
#0 C:\php\bypass.php(330): decryptData('8/8Mnp7WcRph8sb...')
#1 {main}
  thrown in C:\php\bypass.php on line 230
  
  After try to bind "Couldnt verify, wait a minute or two..."
  
![изображение_2024-01-30_144728794](https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/assets/76109635/6dc82daf-ced6-4108-922a-ac4f114a3892)

**Comment by MlgmXyysd** [comment]
#3
