### ISSUE TITLE
The system is being upgraded. Please try again later. (30003) [Redmi Note 13 Pro Plus (zircon)]

### ISSUE THREAD

**Issue by encouragerv** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#46]
I do all steps in "How to use". After binding i got this error (watch screen from PC and Phone). Trying to use MiFlashUnlock after error - nothing happen. Maybe this phone isn't supporting this tool because new SoC?

![Screenshot_4](https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/assets/76109635/8c6bce42-3202-45d2-8f0c-0db6132e0964)
![Screenshot_2024-01-30-17-01-39-455_com android settings](https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/assets/76109635/2153e813-551c-473d-b3fb-cdd89502af87)

**Comment by MlgmXyysd** [comment]
https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/issues/37

**Comment by ninjadev64** [comment]
Hey @encouragerv

I have the same device, did you manage to solve this?
