### ISSUE TITLE
Error reporting consultation

### ISSUE THREAD

**Issue by YunYe-C-X** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#53]
What is the reason for the following problem? How to solve it, the device is Xiaomi 13
![image](https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/assets/145584407/11ccd8d3-fda0-4823-a151-8a207d22aebc)

**Comment by stevleibelt** [comment]
@YunYe-C-X 

What do you get, when you run `php -i`?
Do you see that openssl is installed?
Maybe you have something like grep, than `php -i | grep -i openssl` is the way to go.

The error message is telling you, that it tries to call/execute the command `openssl_decrypt`but the command is not available.

Best regards.

**Comment by YunYe-C-X** [comment]
I have installed openssl and curl using `php -i openssl `and `php -i curl`. I still get the same error when I run it again. What is the reason for this?

**Comment by YunYe-C-X** [comment]
![image](https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/assets/145584407/c30d3a0c-3ee7-4e0e-9982-327dd245bcdd)

**Comment by YunYe-C-X** [comment]
![image](https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/assets/145584407/af6975dd-5cde-49dc-87aa-934a1d509275)

**Comment by YunYe-C-X** [comment]
@stevleibelt Please help me figure out how to proceed with this. Think you~

**Comment by YunYe-C-X** [comment]
Thank you. The problem has been solved. It is a problem with the php.ini file configuration.

**Comment by stevleibelt** [comment]
@YunYe-C-X perfect, good to read. Indeed I was not able to help since I can use Linux or FreeBSD but not Windows.

Best of luck and if you could explain the problem plus a solution, some else will send you good karma in the future!
