### ISSUE TITLE
Request parameter error (10000)

### ISSUE THREAD

**Issue by yarqwq** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#54]
正常连接后，尝试手机端添加账号设备时，CMD 提示Request parameter error (10000)。对于这个报错完全没有头绪，望解答。

**Comment by MlgmXyysd** [comment]
https://www.coolapk.com/feed/53042929?shareKey=NzhmMGE5MTIxOWIwNjVjNDlhMzM~
