### ISSUE TITLE
Binding failed, this device has been forced to verify the account qualification by Xiaomi. (30001)

### ISSUE THREAD

**Issue by AbdElrahmanShaker446** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#59]
i got K70E from china , i live in egypt , i tried this script but it gives me this error : Binding failed, this device has been forced to verify the account qualification by Xiaomi. (30001) , any help please

**Comment by MlgmXyysd** [comment]
> Q: Binding failed with error code 30001.
> A: Your device has been forced to verify the account qualification by Xiaomi. Xiaomi lost its 'geek' spirit a long time ago, and there's nothing we can do about it.

Xiaomi devices sold in mainland China can already be considered not to be allowed to unlock the BootLoader through official channels. you may consider selling the device.

**Comment by AbdElrahmanShaker446** [comment]
> > Q: Binding failed with error code 30001.
> > A: Your device has been forced to verify the account qualification by Xiaomi. Xiaomi lost its 'geek' spirit a long time ago, and there's nothing we can do about it.
> 
> Xiaomi devices sold in mainland China can already be considered not to be allowed to unlock the BootLoader through official channels. you may consider selling the device.

even if reached level 5 on community ?

**Comment by hanxiang-li** [comment]
> > > Q：绑定失败，错误码30001。
> > > A：您的设备已被小米强制验证账号资质。小米早已失去了“极客”精神，对此我们无能为力。
> > 
> > 
> > 在中国大陆销售的小米设备已经可以考虑不允许通过官方渠道解锁BootLoader。您可以考虑出售该设备。
> 
> 即使社区达到5级？

社区5级之后还需要答题，然而这个答题就是故意不让你通过
