### ISSUE TITLE
10000号报错，怎么处理,手机是redmi note 13 pro

### ISSUE THREAD

**Issue by LanSeDiQiu** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#61]
![1](https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/assets/121764616/c1636287-3af0-46e1-bf26-88de991a0bfd)

**Comment by vicdorke** [comment]
替换setting.apk

**Comment by shoshi007** [comment]
> 替换setting.apk

can you help ?

**Comment by nttg430** [comment]
Has anyone had success with Redmi Note 13 Pro-Rom China?

**Comment by shoshi007** [comment]
> Has anyone had success with Redmi Note 13 Pro-Rom China?
no

**Comment by LanSeDiQiu** [comment]
> 替换setting.apk

下载的卡包解包后都是.img文件，但是总是错误，解包不出来system_ext文件，是卡包不对吗

**Comment by ubun222** [comment]
aes解密fail了

**Comment by vicdorke** [comment]
> > 替换setting.apk
> 
> can you help ?

https://www.123pan.com/s/625SVv-TGxbh.html

**Comment by Erixrez** [comment]
I too have the same problem. Before this the script was running fine. For now i manage to solve by using MiCommunity apk by changing region to **Global** and now you can apply for unlocking.

**Comment by asklepios73** [comment]
> I too have the same problem. Before this the script was running fine. For now i manage to solve by using MiCommunity apk by changing region to **Global** and now you can apply for unlocking.

It doen't work in China

**Comment by Erixrez** [comment]
> > I too have the same problem. Before this the script was running fine. For now i manage to solve by using MiCommunity apk by changing region to **Global** and now you can apply for unlocking.
> 
> It doen't work in China

Unninstall the MiCommunity pre built version and download from google.

**Comment by asklepios73** [comment]
Thats what I did. I have been granted access to unlock until next year with MiCommunity, but still cannot add acount and device, 
![image](https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/assets/47295547/e12e6855-3a78-4dc4-8746-8bcd91a2129b)
It seems the code in line 333 doesn't work:
$data["rom_version"] = str_replace("V816", "V14", $data["rom_version"]);

**Comment by SergChe88** [comment]
Open bypass.php in any editor (notepad++ for example), and insert string $data["rom_version"] = ""; before line 333
![Uploading line333.PNG…]()

**Comment by asklepios73** [comment]
It doesn't work:
[2024-03-07] [14:05:24] [INFO] - The system is being upgraded. Please try again later. (30003)

**Comment by SergChe88** [comment]
> It doesn't work: [2024-03-07] [14:05:24] [INFO] - The system is being upgraded. Please try again later. (30003)

Yes, me too. 
Can't bind phone to account.

**Comment by MlgmXyysd** [comment]
Duplicated #37
