### ISSUE TITLE
POCO X6 PRO 5G ERROR

### ISSUE THREAD

**Issue by tonyk-cloud** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#63]
![image](https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/assets/71166954/adac58ec-d8b7-43ff-90fe-548300e00f5b)

Version 1.0.4.0.UNLMIXM

**Comment by awsl1414** [comment]
![image](https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/assets/95275520/af3b1094-27b1-4f0f-9807-ea8b25417a09)

**Comment by awsl1414** [comment]
device：xiaomipad6spro

**Comment by MlgmXyysd** [comment]
Duplicated #29
