### ISSUE TITLE
 Request parameter error (10000)

### ISSUE THREAD

**Issue by LongZijie** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#69]
Account bind request found! Let's block it.
[2024-03-05] [14:41:45] [INFO] - Refactoring parameters...
PHP Warning:  Trying to access array offset on null in C:\PHP\bypass.php on line 333

Warning: Trying to access array offset on null in C:\PHP\bypass.php on line 333
PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in C:\PHP\bypass.php on line 333

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in C:\PHP\bypass.php on line 333
[2024-03-05] [14:41:45] [INFO] - Sending POST request...
[2024-03-05] [14:41:47] [INFO] - Request parameter error (10000)

can pls help?

**Comment by LongZijie** [comment]
![Uploading Screenshot_2024-03-06-12-20-25-169_com.android.settings.jpg…]()

**Comment by LongZijie** [comment]
i am using a 13u cn version, so i should install this settings APK, run the script again, and uninstall the update after bypass, correct? thanks
![Screenshot 2024-03-06 223630](https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/assets/49160401/acdb036c-65cd-4868-9d05-c458e31e651a)

**Comment by LongZijie** [comment]
![Screenshot 2024-03-06 230703](https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/assets/49160401/4cf1540c-3046-4c95-9113-6332ed0a9344)
this means the bypass works alrdy right?

**Comment by LongZijie** [comment]
![Screenshot 2024-03-06 230703](https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/assets/49160401/a68681a5-7e0a-4ea3-b595-ffb49695ac1e)
this means the bypass works alrdy right?

**Comment by LongZijie** [comment]
![Screenshot 2024-03-07 104455](https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/assets/49160401/e08ac083-be91-43a8-b8ff-7f6e721281a5)

**Comment by LongZijie** [comment]
seems it worked. thank u

**Comment by Temeramor** [comment]
Really worked?
What did you do for this?

**Comment by LongZijie** [comment]
> Really worked? What did you do for this?

install the Setting.apk here [Settings_Redmi_marble_V816.0.5.0.UMRINXM.zip](https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/releases/download/1.0-fix/Settings_Redmi_marble_V816.0.5.0.UMRINXM.zip)
