### ISSUE TITLE
php fatal error

### ISSUE THREAD

**Issue by akyolsaid** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#7]
PHP Fatal error:  Uncaught Error: Call to undefined function openssl_decrypt() in C:\Users\Braveril\Desktop\am3\bypass.php:230
Stack trace:
#0 C:\Users\Braveril\Desktop\am3\bypass.php(330): decryptData('8/8Mnp7WcRph8sb...')
#1 {main}
  thrown in C:\Users\Braveril\Desktop\am3\bypass.php on line 230

Fatal error: Uncaught Error: Call to undefined function openssl_decrypt() in C:\Users\Braveril\Desktop\am3\bypass.php:230
Stack trace:
#0 C:\Users\Braveril\Desktop\am3\bypass.php(330): decryptData('8/8Mnp7WcRph8sb...')
#1 {main}
  thrown in C:\Users\Braveril\Desktop\am3\bypass.php on line 230
![image](https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/assets/117091241/702796de-51dd-435c-9277-d078541b23c9)

**Comment by MlgmXyysd** [comment]
#3
