### ISSUE TITLE
Request parameter error (10000) ，override install setting app， 开发者选项闪退

### ISSUE THREAD

**Issue by GuoBoy** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#79]
针对：
Request parameter error (10000) 
通过：
override install setting app， 
但是：
开发者选项闪退，无法执行绑定操作
————————————————————
设备信息：
redmik60 utlra
hyperos 1.0.9
————————————————————
不知道大佬有没有研究出新的解决策略

**Comment by GuoBoy** [comment]
It's resolved by some version setting apk.

**Comment by XTian666** [comment]
如何解决的 教浇

**Comment by XTian666** [comment]
谢谢你 我已经找到解决方案了，下载到了对应版本 感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月26日(星期二) 晚上8:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass] Request parameter error (10000) ，override install setting app， 开发者选项闪退 (Issue #79)





  
如何解决的 教浇
  
You need to overinstall other version setting.apk that is suitable with your phone. I found a resouce from some blog, but I forget to save, you can search with browser.
 And, with some ressaon, I have updated to hypeos again.
