### ISSUE TITLE
 Request parameter error (10000)

### ISSUE THREAD

**Issue by Gesundheitsvorsorge** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#80]
why?

**Comment by LeanFly** [comment]
https://www.123pan.com/s/625SVv-BYxbh.html

从上面网盘下载setting.apk，安装后重启手机

**Comment by Gesundheitsvorsorge** [comment]
this is ok.thanks

**Comment by vnvyvu** [comment]
> https://www.123pan.com/s/625SVv-BYxbh.html
> 
> 从上面网盘下载setting.apk，安装后重启手机

can I have gg drive url?

**Comment by Gesundheitsvorsorge** [comment]
> > https://www.123pan.com/s/625SVv-BYxbh.html
> > 
> > 从上面网盘下载setting.apk，安装后重启手机
> 
> can I have gg drive URL https://drive.google.com/file/d/1-Ht6fstbbNCOmnWh9-s58CzWeCPLlNhl/view?usp=drivesdk 
only K60Pro
