### ISSUE TITLE
Request parameter error (10000)

### ISSUE THREAD

**Issue by Sreehari1710** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#88]
I tried the settings.apk in the solved section but after installing the apk I wasn't able to access the developer settings.

"ROM VERSION" is coming up as  null.

[2024-03-25] [10:28:00] [INFO] - Account bind request found! Let's block it.
[2024-03-25] [10:28:00] [INFO] - Refactoring parameters...
PHP Warning:  Trying to access array offset on value of type null in C:\php\bypass.php on line 333

Warning: Trying to access array offset on value of type null in C:\php\bypass.php on line 333
[2024-03-25] [10:28:00] [INFO] - Sending POST request...
[2024-03-25] [10:28:00] [INFO] - Request parameter error (10000)

**Comment by Ryancheng236** [comment]
I got same problem. Do you resolve this?

**Comment by LeanFly** [comment]
https://www.123pan.com/s/625SVv-BYxbh.html

从上面网盘下载setting.apk，安装后重启手机

**Comment by Ryancheng236** [comment]
谢谢啦！！！



---Original---
From: ***@***.***&gt;
Date: Wed, Mar 27, 2024 14:57 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass] Request parametererror (10000) (Issue #88)




 
https://www.123pan.com/s/625SVv-BYxbh.html
 
从上面网盘下载setting.apk，安装后重启手机

**Comment by ZawPhoneMaw** [comment]
I got same issues. After installing setting.apk, can't open developer option. Crashing again & again
Any solution for unlock bootloader Plz!!!

**Comment by ketor** [comment]
> I got same issues. After installing setting.apk, can't open developer option. Crashing again & again Any solution for unlock bootloader Plz!!!

Got same issues on Redmi K60 Ultra( Running HyperOS 1.0.9.0)。 Maybe this solution is not work now.

**Comment by MoutainPL** [comment]
> https://www.123pan.com/s/625SVv-BYxbh.html
> 
> 从上面网盘下载setting.apk，安装后重启手机

not work

**Comment by LananaHWP** [comment]
> > https://www.123pan.com/s/625SVv-BYxbh.html
> > 从上面网盘下载setting.apk，安装后重启手机
> 
> not work

disable bluetooth, then it works

**Comment by ketor** [comment]
After download settings.apk from the 123pan,  I have unlocked K60 ultra with the latest hyperos 1.0.11.0.
Thanks very much!

**Comment by eddiemukri01** [comment]
![Screenshot_2024-07-17-23-16-52-497_com miui packageinstaller](https://github.com/user-attachments/assets/9886a004-9298-43c5-9ff1-59769b79af7f)

How can i install setting.apk?

**Comment by bdd786** [comment]
How can we install settings.apk, it says app not installed as package appears to be invalid. It tries to update the original settings app
