### ISSUE TITLE
Uncaught Error: Call to undefined function openssl_decrypt()

### ISSUE THREAD

**Issue by alva1018** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#91]
![Screenshot 2024-04-05 223417](https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/assets/3016733/bc1bc3b3-7969-48e9-91da-1f7737b86a15)
出现这个问题，php.ini设置里curl和openssl都打开了
![image](https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/assets/3016733/c381882a-f89b-4be2-930c-abed6f75cea7)

请教解决方法，多谢多谢！！

**Comment by alva1018** [comment]
已解决。。配置文件路径问题，放入C盘根目录就OK了，惭愧

**Comment by W1LLY-W0N** [comment]
Hello !

I think I am experiencing the same issue as you. How did you do to solve it ?

**Comment by alva1018** [comment]
Put all the files into the directory "C:" should resolve the problem. It seems to be related to the address specified in the configuration file.

________________________________

**Comment by TriarOriginalSin** [comment]
我也遇到了相似的问题，把文件夹或文件放入C:\均无效，求助

**Comment by Abdurrahman98XX** [comment]
same problem here, why is it close if there is not an answer?
