### ISSUE TITLE
Stuck on "you can bind account..."

### ISSUE THREAD

**Issue by YaroslavQw** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#93]
Stuck on "you can bind account in the developer options"
Device Xiaomi pad 6 pro
Rom hyperos 1.0.4.0cn

**Comment by YaroslavQw** [comment]
![IMG_20240407_183843](https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/assets/166317109/f91b3002-757f-4270-a896-b72fc2806b5b)

**Comment by kbiits** [comment]
It's waiting you to try to add your mi account. You need to interact with your phone, go to mi unlock status and try to add account.

**Comment by YaroslavQw** [comment]
Unfortunately, the problem is that nothing happens after I try to add an account in the developer settings "couldn't add. Please go to mi community".

**Comment by kbiits** [comment]
Yes, that is the purpose. We need to intercept the request when you try to add an account, make a modification to the request, and send it again. So, it's expected to fail, just see your terminal output

**Comment by kbiits** [comment]
If it succeeded you will see message "Your account was bound successfully" in your terminal output

**Comment by YaroslavQw** [comment]
But the problem is that nothing is happening. Nothing at all

**Comment by YaroslavQw** [comment]
It's fix after format data

**Comment by yash96644** [comment]
did u figure out this issue
