### ISSUE TITLE
PHP Fatal Error: Uncaught Error

### ISSUE THREAD

**Issue by xShihaBx** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#97]
PHP Fatal error:  Uncaught Error: Call to undefined function openssl_decrypt() in C:\Program Files\php-8.3.6\bypass.php:230
Stack trace:
#0 C:\Program Files\php-8.3.6\bypass.php(330): decryptData('#&^aUI6UDY9VJc6...')
#1 {main}
  thrown in C:\Program Files\php-8.3.6\bypass.php on line 230

Fatal error: Uncaught Error: Call to undefined function openssl_decrypt() in C:\Program Files\php-8.3.6\bypass.php:230
Stack trace:
#0 C:\Program Files\php-8.3.6\bypass.php(330): decryptData('#&^aUI6UDY9VJc6...')
#1 {main}
  thrown in C:\Program Files\php-8.3.6\bypass.php on line 230
![image_2024-04-16_170517137](https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/assets/106065024/69948952-7b1d-4529-811a-6e0c0fd1586f)

**Comment by sword-jin** [comment]
没有开启 openssl 拓展
https://www.php.net/manual/en/install.pecl.windows.php
