### ISSUE TITLE
Request parameter error (10000)

### ISSUE THREAD

**Issue by xShihaBx** [MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass#98]
![Screenshot 2024-04-17 143450](https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/assets/106065024/47298ab2-6a1a-4737-8392-2a1fe79f4905)

**Comment by smile-YYY** [comment]
You can install the new settings app, then log in to your Xiaomi account again, connect the phone to the computer to unlock it, this is how I solved the problem

**Comment by xbn2002** [comment]
Look https://github.com/MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass/issues/82 pls
And if you can't open developer options after downgrade, then find another one until it works.

**Comment by xShihaBx** [comment]
I don't understand Chinese. Could you please help me ?

**Comment by xShihaBx** [comment]
I did everything that was shown in that video.

**Comment by ColderCoder** [comment]
>  And if you can't open developer options after downgrade, then find another one until it works.

do a factory reset if downgraded Settings crash while opening developer options
* yeah that means you will have to lose all your data again in 168h. don't forget to backup your phone

**Comment by xShihaBx** [comment]
downgraing system app is not possible. How can I download?

**Comment by jadson110** [comment]
Request Paramenter error (10000)

![Image](https://github.com/user-
attachments/assets/5af60bb4-770b-48b0-868f-715dbceea15c)
